export const accompanyList = [
  // {
  //   id: 1, // 데이터고유아이디
  //   memberId: 4, // 글생성자 유저아이디
  //   writerName: 'hi1', // 작성자 닉네임
  //   accompanyLocal: '서울', // 지역
  //   accompanyDate: '2023-06-11', // 날짜
  //   maxNum: 5, // 총원
  //   accompanyTitle: '제목1', // 제목
  //   accompanyContent: '내용1', // 내용
  //   openStatus: true, // 모집중인지 마감인지
  //   createdAt: null, // 생성날짜
  //   modifiedAt: null, // 수정날짜
  // },
  {
    id: 1,
    memberId: 1,
    writerName: '철수',
    accompanyLocal: '서울',
    accompanyDate: '2023-07-01',
    maxNum: 5,
    accompanyTitle: '같이 돌하르방 보러가요오오오오오오오오 보러가요오오오오오오오오',
    accompanyContent:
      '고고고고고고고고고고고고고고고고고고고고고고고고고고고고고고고고고고고고고고고고고고고고고고고고고고고고',
    openStatus: true,
    createdAt: null,
    modifiedAt: null,
  },
  {
    id: 2,
    memberId: 2,
    writerName: '철수',
    accompanyLocal: '서울',
    accompanyDate: '2023-07-01',
    maxNum: 5,
    accompanyTitle: '같이 돌하르방 보러가요',
    accompanyContent: '고고고고',
    openStatus: true,
    createdAt: null,
    modifiedAt: null,
  },
  {
    id: 3,
    memberId: 3,
    writerName: '철수',
    accompanyLocal: '서울',
    accompanyDate: '2023-07-01',
    maxNum: 5,
    accompanyTitle: '같이 돌하르방 보러가요',
    accompanyContent: '고고고고',
    openStatus: true,
    createdAt: null,
    modifiedAt: null,
  },
  {
    id: 4,
    memberId: 4,
    writerName: '철수',
    accompanyLocal: '서울',
    accompanyDate: '2023-07-01',
    maxNum: 5,
    accompanyTitle: '같이 돌하르방 보러가요',
    accompanyContent: '고고고고',
    openStatus: true,
    createdAt: null,
    modifiedAt: null,
  },
  {
    id: 5,
    memberId: 5,
    writerName: '철수',
    accompanyLocal: '서울',
    accompanyDate: '2023-07-01',
    maxNum: 5,
    accompanyTitle: '같이 돌하르방 보러가요',
    accompanyContent: '고고고고',
    openStatus: true,
    createdAt: null,
    modifiedAt: null,
  },
  {
    id: 6,
    memberId: 6,
    writerName: '철수',
    accompanyLocal: '서울',
    accompanyDate: '2023-07-01',
    maxNum: 5,
    accompanyTitle: '같이 돌하르방 보러가요',
    accompanyContent: '고고고고',
    openStatus: true,
    createdAt: null,
    modifiedAt: null,
  },
  {
    id: 7,
    memberId: 7,
    writerName: '철수',
    accompanyLocal: '서울',
    accompanyDate: '2023-07-01',
    maxNum: 5,
    accompanyTitle: '같이 돌하르방 보러가요',
    accompanyContent: '고고고고',
    openStatus: true,
    createdAt: null,
    modifiedAt: null,
  },
  {
    id: 8,
    memberId: 8,
    writerName: '철수',
    accompanyLocal: '서울',
    accompanyDate: '2023-07-01',
    maxNum: 5,
    accompanyTitle: '같이 돌하르방 보러가요',
    accompanyContent: '고고고고',
    openStatus: true,
    createdAt: null,
    modifiedAt: null,
  },
  {
    id: 9,
    memberId: 9,
    writerName: '철수',
    accompanyLocal: '서울',
    accompanyDate: '2023-07-01',
    maxNum: 5,
    accompanyTitle: '같이 돌하르방 보러가요',
    accompanyContent: '고고고고',
    openStatus: true,
    createdAt: null,
    modifiedAt: null,
  },
];
